# Generated by Django 4.2.5 on 2023-09-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('description', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('brand', models.CharField(max_length=50)),
                ('tyreimage', models.ImageField(upload_to='products')),
            ],
        ),
    ]
