# Generated by Django 4.2.5 on 2023-09-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhamonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
