# Generated by Django 4.2.5 on 2023-09-25 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PhamonApp', '0002_productitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('firstname', models.TextField(max_length=30)),
                ('lastname', models.TextField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('address', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brand', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhamonApp.productitem')),
            ],
        ),
    ]
